site_name: RxTx
site_description: >-
   RxTx offers consulting services for scientific software, including
   development, testing, documentation writing, and deployment.
site_author: Vedran Miletić
site_url: 'https://rxtxresearch.github.io/'
copyright: >-
  Copyright 2019 – 2022, RxTx. All rights reserved. <a href="#__consent">Change
  cookie settings</a>.
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.follow
  logo: images/rxtx-symbol-white.svg
  favicon: images/favicon.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
plugins:
  - search
  - social
extra:
  analytics:
    provider: google
    property: G-7JJSME8LFR
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/company/rxtx'
      name: RxTx on LinkedIn
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/RxTxResearch'
      name: RxTx Research on Twitter
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCBDDGDnCECrJAZcoYT1IT4Q'
      name: RxTx Research on YouTube
    - icon: fontawesome/brands/github
      link: 'https://github.com/rxtxresearch'
      name: RxTx Research on GitHub
    - icon: fontawesome/brands/gitlab
      link: 'https://gitlab.com/rxtx'
      name: RxTx on GitLab
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.superfences
